#!/bin/sh /etc/rc.common

START=14
STOP=96

USE_PROCD=1
NAME=dslmngr

start_service() {
	procd_open_instance
	procd_set_param command "/sbin/dslmngr"
	procd_set_param respawn
	procd_close_instance
}

service_running() {
        ubus -t 5 wait_for xdsl
        ubus -t 5 call xdsl start
}

service_triggers()
{
	procd_add_reload_trigger dsl
}

reload_service() {
	ubus -t 5 call xdsl stop
	ubus -t 5 call xdsl start
}

