#!/bin/sh

case $INTERFACE in
	eth0_*) exit 0 ;;
esac

[ "$ACTION" = ifup -o "$ACTION" = ifupdate ] || exit 0
[ "$ACTION" = ifupdate -a -z "$IFUPDATE_ADDRESSES" -a -z "$IFUPDATE_DATA" ] && exit 0

/etc/init.d/mcproxy restart

logger -t mcproxy "Reloading mcproxy due to $ACTION of $INTERFACE ($DEVICE)"
